services:
  backend:
    build: .
    container_name: rentacar_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - IYZICO_API_KEY=sandbox-dWwyWcQHp2nNUYhBxfD9dQzB3FyuCEBA
      - IYZICO_SECRET_KEY=sandbox-eLeyIz2gbPqe2nUkeXwPpJsslk3KPyI8
      - IYZICO_BASE_URL=sandbox-api.iyzipay.com
      # Email ayarları (.env dosyasından okunur)
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_FROM=${MAIL_FROM:-}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: rentacar_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rentacar
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
